
# Smallrye JMS configuration
mp.messaging.connector.smallrye-jms.connection-factory-name=ibm-mq-factory
mp.messaging.connector.smallrye-jms.reuse-jms-context=true

mp.messaging.incoming.ibm-mq-in-1.connector=smallrye-jms
mp.messaging.incoming.ibm-mq-in-1.destination=DEV.QUEUE.1

mp.messaging.incoming.ibm-mq-in-2.connector=smallrye-jms
mp.messaging.incoming.ibm-mq-in-2.destination=DEV.QUEUE.2


# IBM MQ configuration
ibmmq.queue-managers."QM8".host-name=localhost
ibmmq.queue-managers."QM8".port=1414
ibmmq.queue-managers."QM8".queue-manager=QM8
ibmmq.queue-managers."QM8".channel=DEV.APP.SVRCONN
ibmmq.queue-managers."QM8".app-name=test-app
ibmmq.queue-managers."QM8".user-id=app
ibmmq.queue-managers."QM8".password=passw0rd
ibmmq.queue-managers."QM8".transport-type=1

ibmmq.queue-managers."QM8".queues."dev-queue-1".name=DEV.QUEUE.1
ibmmq.queue-managers."QM8".queues."dev-queue-1".modality=DEV1

ibmmq.queue-managers."QM8".queues."dev-queue-2".name=DEV.QUEUE.2
ibmmq.queue-managers."QM8".queues."dev-queue-2".modality=DEV2

# Servicebus configuration
quarkus.log.category."com.azure".level=WARN

servicebus.namespaces."otav.dev".connection-string=${SERVICEBUS_OTAV_DEV_CONNECTION_STRING}
servicebus.namespaces."otav.dev".queue."otav.test".name=otav.test
servicebus.namespaces."otav.dev".queue."otav.test".resilience.timeout-queue=otav.test.timeout
servicebus.namespaces."otav.dev".queue."otav.test".resilience.timeout-retry-delay-seconds=300
servicebus.namespaces."otav.dev".queue."otav.test".resilience.restart-delay-seconds=30
