
mp.messaging.connector.smallrye-jms.connection-factory-name=ibm-mq-factory

mp.messaging.incoming.ibm-mq-in.connector=smallrye-jms
mp.messaging.incoming.ibm-mq-in.destination=DEV.QUEUE.1

smallrye.messaging.worker.my-custom-pool.max-concurrency=2

# Servicebus configuration
quarkus.log.category."com.azure".level=WARN

# Namespace: otav.dev
servicebus.namespaces."otav.dev".queue."otav.test".name=otav.test
servicebus.namespaces."otav.dev".queue."otav.test".connection-string=${SERVICEBUS_OTAV_DEV_QUEUE_OTAV_TEST_CONNECTION_STRING}
